{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-ktx",
    "version": "1.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "6953474"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.5.0-alpha05.aar",
          "url": "core-ktx-1.5.0-alpha05.aar",
          "size": 164691,
          "sha512": "7d1403c319e3ad45d8d2c1aa4bf0365e5a26eac82957079d9e01320e399d692671337dcef558bdc0d570d0be03e0bbc10b9294475a18232c349dc714083043ec",
          "sha256": "d0e5ceffc94be64820741dd2841cb6cbac38321b3e9943cc154aafe13995b64e",
          "sha1": "3427e7fdb0cb790d0fe582d61bd121bed87f522a",
          "md5": "14f8c529648f3f2de1f4ba6d34adce59"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.5.0-alpha05.aar",
          "url": "core-ktx-1.5.0-alpha05.aar",
          "size": 164691,
          "sha512": "7d1403c319e3ad45d8d2c1aa4bf0365e5a26eac82957079d9e01320e399d692671337dcef558bdc0d570d0be03e0bbc10b9294475a18232c349dc714083043ec",
          "sha256": "d0e5ceffc94be64820741dd2841cb6cbac38321b3e9943cc154aafe13995b64e",
          "sha1": "3427e7fdb0cb790d0fe582d61bd121bed87f522a",
          "md5": "14f8c529648f3f2de1f4ba6d34adce59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ktx-1.5.0-alpha05-sources.jar",
          "url": "core-ktx-1.5.0-alpha05-sources.jar",
          "size": 62086,
          "sha512": "766a3f6a2cc8e54f130b8cc6fa72c74e959943d853741848937373cdf04a0c9774a6e710762587a2c9cd3cffebfc87aaee5786d055700e50649e6f12e5135708",
          "sha256": "9643ced6a1e132a68dcc1d4bf35237222c172bfb129f56b90bf8054c707ce809",
          "sha1": "7413c15f86af78773a149fcdc9640237da36545c",
          "md5": "1bc6bd053ca0162d4aeeddc5b479fbfa"
        }
      ]
    }
  ]
}
